name               = "daylighthealth"
account_id         = "c01c7dbd930d959df746f7c02165f34b"   # ← your real Cloudflare account ID
compatibility_date = "2025-04-20"
compatibility_flags = ["nodejs_compat"]

# Must point directly at the generated index.js, not the folder
main = ".vercel/output/static/_worker.js/index.js"

[site]
  bucket = ".vercel/output/static"

[vars]
  NEXT_RUNTIME = "edge"
