name               = "daylighthealth"
account_id         = "c01c7dbd930d959df746f7c02165f34b"
compatibility_date = "2025-04-20"
compatibility_flags = ["nodejs_compat"]

main = ".vercel/output/functions/index.func/index.js"

[site]
  bucket = ".vercel/output/static"

[vars]
  NEXT_RUNTIME = "edge"
