name               = "daylighthealth"
account_id         = "c01c7dbd930d959df746f7c02165f34b" 
compatibility_flags = ["nodejs_compat"]

[site]
  bucket      = ".vercel/output/static"
  entry-point = ".vercel/output/functions"
