name               = "daylighthealth"
account_id         = "c01c7dbd930d959df746f7c02165f34b"     
compatibility_date = "2025-04-20"
compatibility_flags = ["nodejs_compat"]

main = ".vercel/output/static/_worker.js/index.js"

# serve all of your prerendered HTML/CSS/JS here
[site]
bucket = ".vercel/output/static"

[vars]
NEXT_RUNTIME = "edge"
